# Rust formatting configuration
edition = "2021"
use_field_init_shorthand = true
use_small_heuristics = "Max"
imports_granularity = "Module"
group_imports = "StdExternalCrate"
format_code_in_doc_comments = true
format_strings = true
wrap_comments = true
comment_width = 100
normalize_comments = true