name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  extension-quality:
    name: Extension Code Quality
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run ESLint
      run: npm run lint
    
    - name: Run tests
      run: npm test

  daemon-quality:
    name: Daemon Code Quality
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        components: clippy, rustfmt
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libpipewire-0.3-dev libspa-0.2-dev pkg-config
    
    - name: Check formatting
      run: cargo fmt --manifest-path=daemon/Cargo.toml -- --check
    
    - name: Run Clippy
      run: cargo clippy --manifest-path=daemon/Cargo.toml -- -D warnings
    
    - name: Run tests
      run: cargo test --manifest-path=daemon/Cargo.toml

  code-quality-summary:
    name: Code Quality Summary
    needs: [extension-quality, daemon-quality]
    runs-on: ubuntu-latest
    if: always()
    steps:
    - name: Check results
      run: |
        if [ "${{ needs.extension-quality.result }}" != "success" ] || [ "${{ needs.daemon-quality.result }}" != "success" ]; then
          echo "Code quality checks failed!"
          exit 1
        fi
        echo "All code quality checks passed!"